apiVersion: amida.harukin721.github.io/v1
kind: Amida
metadata:
  labels:
    app.kubernetes.io/name: amida
    app.kubernetes.io/instance: amida-sample
    app.kubernetes.io/part-of: amida
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: amida
  name: amida-sample
spec:
  amida:
    results:
      - result1
      - result2
    selectCount: 2
    selects:
      - select1
      - select2
