# permissions for end users to edit amida.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: amida-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: amida
    app.kubernetes.io/part-of: amida
    app.kubernetes.io/managed-by: kustomize
  name: amida-editor-role
rules:
- apiGroups:
  - amida.harukin721.github.io
  resources:
  - amida
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - amida.harukin721.github.io
  resources:
  - amida/status
  verbs:
  - get
